@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri May 26 15:07:14 +0200 2023
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 9f1aa4d5307442d19de922d7d674ff35 --incr --debug typical --relax --mt 2 -L xbip_utils_v3_0_10 -L dft_v4_1_1 -L xil_defaultlib -L secureip -L xpm --snapshot Visualizer_TB_behav xil_defaultlib.Visualizer_TB -log elaborate.log"
call xelab  -wto 9f1aa4d5307442d19de922d7d674ff35 --incr --debug typical --relax --mt 2 -L xbip_utils_v3_0_10 -L dft_v4_1_1 -L xil_defaultlib -L secureip -L xpm --snapshot Visualizer_TB_behav xil_defaultlib.Visualizer_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
