@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 25 14:12:37 +0200 2023
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Visualizer_TB_func_synth -key {Post-Synthesis:sim_1:Functional:Visualizer_TB} -tclbatch Visualizer_TB.tcl -view C:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Visualizer_TB_behav.wcfg -log simulate.log"
call xsim  Visualizer_TB_func_synth -key {Post-Synthesis:sim_1:Functional:Visualizer_TB} -tclbatch Visualizer_TB.tcl -view C:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Visualizer_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
