# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT.xci
# IP: The module: 'DFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT.xci
# IP: The module: 'DFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/G/CODE/proj_Vivado/FPGA-Audio-Visualizer/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
