# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.cache/wt [current_project]
set_property parent.project_path C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/ADAU1761_interface.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/new/DFT_TOP.vhd}
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/new/RAM_mag.vhd
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Video/Design_TB_Sources/VGA.vhd
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Video/Design_TB_Sources/Video_top.vhd
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/Visualizer beta/Wave_32_as4.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/adau1761_configuraiton_data.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/adau1761_izedboard.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/audio_top.vhd}
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Video/Design_TB_Sources/clock_div.vhd
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/clocking.vhd}
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/DFT/counter.vhd
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/i2c.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/i2s_data_interface.vhd}
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/adau1761 driver vhdl/i3c2.vhd}
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/DFT/magnitude_calculator.vhd
  C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Video/Design_TB_Sources/pattern_generator.vhd
  {C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/imports/FPGA-Audio-Visualizer/Visualizer beta/new/Visualizer_top.vhd}
}
read_ip -quiet C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT.xci
set_property used_in_implementation false [get_files -all c:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/sources_1/ip/DFT/DFT_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/constrs_1/imports/XDC/zedboard_master.xdc
set_property used_in_implementation false [get_files C:/Users/games/OneDrive/Skrivebord/FPGA-Audio-Visualizer-main/Audio_Visualizer/Audio_Visualizer.srcs/constrs_1/imports/XDC/zedboard_master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Visualizer -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Visualizer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Visualizer_utilization_synth.rpt -pb Visualizer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
